# -*- coding: utf-8 -*-
"""YBI-DS-Intern-Project-Anand-Yadav.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cNMb3AfeR-W8aVgYXjwtf6ciVGIf01cQ

# Chance Of Admission for Higher Studies Prediction with Machine Learnig
"""

# Step 1: import libraries
import pandas as pd

# Step 2: import data
admission = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Admission%20Chance.csv')

# Basic Visualization of dataset

admission.head()

admission.info()

admission.describe()

# Step 3: define target(y) and features(X)

admission.columns

y = admission['Chance of Admit ']

X = admission[['GRE Score', 'TOEFL Score', 'University Rating', ' SOP', 'LOR ', 'CGPA', 'Research']]

# Step 4 : train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7, random_state=2529)

# Step 5: Model Selection
from sklearn.linear_model import LinearRegression
model = LinearRegression()

# Step 6: Model Fitting
model.fit(X_train, y_train)

model.intercept_

model.coef_

# Step 7: Model Prediction
y_pred = model.predict(X_test)

# Step 8: Model Evaluation

from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test, y_pred)

from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

